### PR TITLE
Add eval command

### PR DESCRIPTION
**Pull request by ShadowKA**
This command allows JavaScript code to be input and a value be returned.
**This command is only limited to the bot owners, Jett#2782 (ID: 218397146049806337) and Jonah Yordy#9673 (ID: 309845156696424458). Nobody else should be allowed to use this command, it gives someone full access to the bot.**

### CODE REVIEW

**Comment by ShadowKA** [comment]
I'm going to add another commit that will update the code to the latest commit on the JettBurns14/Discord-tool-bot branch

**Comment by Dopest-Pleb** [comment]
Looks good!  Did you add the clean function tho?  (Is that a face reveal Jett?)

**Comment by ShadowKA** [comment]
The conflict is because there's been commits since this process was submitted. I'll clear those conflicts soon. I'll also add the clear function there if it wasn't added before.

**Comment by Dopest-Pleb** [comment]
@ShadowKA Sounds good @JettBurns14 noice

**Comment by JettBurns14** [comment]
@ShadowKA is this ready to go? I'd like to merge.

**Comment by ShadowKA** [comment]
Sorry, forgot about this. I'll have time to grab the clean function and add it this afternoon.

**Comment by ShadowKA** [comment]
This should be ready to go. _Wishes the rainbowblob feature had been merged to patch-5 so I could add my ID to it 😄_

**Pull request merged**
